### ISSUE TITLE
  Processing of Constraint Expressions

### ISSUE THREAD

**Issue by fanghejun** [HexHive/Igor#8]
How did you implement the cleaning of constraint expressions mentioned in your work and ultimately compare their similarity in the form of AST? I couldn't find it in the complex warehouse code, and if possible, I hope you can give me a chance to learn this part of the code.Thanks!

**Comment by fanghejun** [comment]
I am very interested in your work and hope to receive your reply!

**Comment by tiedaoxiaotubie** [comment]
I don't think we have ever mentioned constraint experssion and compare them in Igor, could you please tell me where you got this information? I think this part of work should be our next work, we regard it as IgorNG, which is not public yet, it is weird you are familar with this work in advance. The implementation of IgorNG has been finished, but the paper is not, we are still pushing the writing now. Please let me know who you are and which lab you belong to, maybe we can share the code with you in private. You can ping me via my e-mail :)

**Comment by fanghejun** [comment]
I have carefully studied your paper, and I am very interested in the "bug context" you mentioned. I am also exploring Symbolic execution tools, including the situation that I saw a work before that is also a whole mapping AST of program runtime information, so I want to ask you about this problem. The specific situation has been sent to you via email~Looking forward to a reply

**Comment by fanghejun** [comment]
Also, I wish you a smooth posting and hope to read your article soon:)

**Comment by tiedaoxiaotubie** [comment]
The student has contacted us in private, so this issue should be closed.
